[tox]
envlist = py37, py38, py39, py310, py311, py312, py313

[testenv]
deps = pytest>=8
commands_pre =
    python -m pip install --upgrade pip setuptools wheel
    python -m pip install -e .
commands = pytest {posargs}
