name: Build and publish wheels

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels (3.9-3.14)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v7

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1
        env:
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
          CIBW_BUILD: "cp3{9,10,11,12,13,14}-*"
          CIBW_SKIP: "cp3??t-*"
          CIBW_TEST_REQUIRES: tox
          CIBW_TEST_COMMAND: >
            cd {project} &&
            python -c "import sys, subprocess; env='py{}{}'.format(*sys.version_info[:2]); exit(subprocess.call(['tox', '-e', env, '--', '-v']))"
          CIBW_TEST_COMMAND_WINDOWS: >
            cd {project} &&
            python -c "import sys, subprocess; env='py{}{}'.format(*sys.version_info[:2]); exit(subprocess.call(['tox', '-e', env, '--', '-v']))"
          CIBW_BUILD_VERBOSITY: 1

      - name: Store wheels
        uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  publish:
    name: Publish wheels to PyPI
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build_wheels]
    runs-on: ubuntu-latest

    steps:
      - name: Create dist directory
        run: mkdir -p dist

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: wheels-*
          path: all-wheels
          merge-multiple: false

      - name: Move all wheels to dist directory
        run: |
          find all-wheels -type f -name "*.whl" -exec cp {} dist/ \;
          ls -la dist/

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Twine
        run: |
          pip install --upgrade twine

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TGCRYPTO2 }}
        run: |
          twine check dist/*
          twine upload dist/*
